version: "3.5"

services:
  eureka:
    container_name: registry-service
    build: .
    restart: always
    ports:
      - 8099:8099
    networks:
      - bank-network

networks:
  bank-network:
    external: 
      name: bank-network